---
apiVersion: v1
kind: Service
metadata:
  name: go-echo-practice-api
spec:
  selector:
    app: go-echo-practice-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo-practice-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-echo-practice-api
  template:
    metadata:
      labels:
        app: go-echo-practice-api
    spec:
      containers:
        - name: go-echo-practice-api
          image: faruryo/go-echo-practice
          imagePullPolicy: Never
